// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmprpfblzjsigymqhsfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtcHJwZmJsempzaWd5bXFoc2Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODkwNjAsImV4cCI6MjA2NTI2NTA2MH0.8LhDDWYZO1ZGs5ifSWD37Nr41T7hwRtwZA9D-iJgpOo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);